services:
  postgres-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./data/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    networks:
      - postgres-network
    ports:
      - "5432:5432"
    

  postgres-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./data/pgadmin_data:/var/lib/pgadmin"
    networks:
      - postgres-network
    ports:
      - "8080:80"
networks:
  postgres-network:
    external: true
volumes:
  ny_taxi_postgres_data:
  pgadmin_data:
