version: 2

sources:
    - name: staging
      database: ny-rides-share-jao    # cannot have dashes
      schema: trips_data_all

      tables:
        - name: green_tripdata
        - name: yellow_tripdata